using DeterministicIsland.domain;

namespace DeterministicIsland.Islands
{
    // The safety facts this POC keeps in the Static Vault. Each one is a query whose
    // answer is pre-verified and human-approved, never generated by the AI core.
    public static class SafetyLimits
    {
        public const string MaxAiValveOpening = "maximum safe valve opening for ai-proposed commands";
        public const string PressureReliefSetpointBar = "high pressure relief setpoint in bar";
        public const string PressureReliefValveOpening = "valve opening for high pressure relief";
        public const string CoolantTemperatureLimitCelsius = "maximum coolant temperature in celsius";
        public const string StructuralCoolingValveOpening = "valve opening for structural cooling";
        public const string RadiationContainmentValveOpening = "valve opening for radiation containment";

        public static void SeedDefaults(StaticVault vault, DateTime validFrom, string approvedBy)
        {
            vault.Register(MaxAiValveOpening, 0.75, validFrom, approvedBy);
            vault.Register(PressureReliefSetpointBar, 8.0, validFrom, approvedBy);
            vault.Register(PressureReliefValveOpening, 1.0, validFrom, approvedBy);
            vault.Register(CoolantTemperatureLimitCelsius, 90.0, validFrom, approvedBy);
            vault.Register(StructuralCoolingValveOpening, 0.6, validFrom, approvedBy);
            vault.Register(RadiationContainmentValveOpening, 0.0, validFrom, approvedBy);
        }

        // A missing safety limit is a dangling reference and must fail loudly (§12.3.3),
        // never fall back to a value the AI core produced.
        public static ILMVector Require(StaticVault vault, string query, DateTime asOf) =>
            vault.Lookup(query, asOf)
            ?? throw new InvalidOperationException($"Safety limit '{query}' is not registered in the Static Vault at {asOf:O}.");

        public static string Describe(string query, ILMVector vector) =>
            $"{query} = {vector.Value} ({vector.Determinism!.Version}, approved by {vector.Determinism.ApprovedBy})";
    }
}
